[font]
normal = { family = "CaskaydiaMono Nerd Font", style = "Regular" }
size = 14

[window]
padding = { x = 1, y = 0 }
opacity = 1

[general]
import = [
    "~/.config/alacritty/themes/adventure.toml"
]
