# Search text
alias grep='grep --color'
alias egrep='grep --color -E'
alias fgrep='grep --color -F'

# Install exa
if [ -x "$(command -v exa)" ]; then
    alias ls='exa --icons'
    alias ll='exa -lh --icons'
    alias la='exa -a --icons'
    alias lla='exa -lha --icons'
    alias tree='exa -T --icons'
else
    alias ls='ls --color'
    alias ll='ls --color -lFh'
    alias la='ls --color -a'
    alias lla='ls --color -lFha'
fi
alias l.="/bin/ls -A | grep -E '^\.'"

# Install bat
if [ -x "$(command -v bat)" ]; then
    alias cat='bat --paging=never --style=plain'
fi

alias reload='source $HOME/.bashrc'
alias dotfiles='cd $HOME/.dotfiles'

# Install neovim
if [ -x "$(command -v nvim)" ]; then
    alias v='nvim'
else
    alias v='vim'
fi

alias ctrlc="xclip -selection clipboard"
alias ctrlv="xclip -selection clipboard -o"

# Readable output
alias df='df -h'
alias du='du -h'

# Continue download
wgetc='wget -c'

# Better readable
alias free="free -mt"
