#!/bin/bash

show_help() {
    echo "Usage: $(basename $0) <title> [<project>] [<repository-name-or-id>] [<target-branch>] [<source-branch>]"
    echo ""
    echo "Create a PR in Azure DevOps."
    echo ""
    echo ""
    echo "Arguments:"
    echo "  <title>                   Title of the PR. (Required)"
    echo "  <project>                 (Optional) Project name of the repository. Default: Juntoz"
    echo "  <repository-name-or-id>   (Optional) Name or ID of the repository. Default: current directory name"
    echo "  <target-branch>           (Optional) Target branch of the repository. Default: master"
    echo "  <source-branch>           (Optional) Source branch of the repository. Default: current branch"
    echo ""
}

title=$1
project=$2
repository=$3
target_branch=$4
source_branch=$5

if [ $# -lt 1 ]; then
    show_help
    exit 1
fi

if [[ -z "$project" ]]; then
    project=Juntoz
fi

if [[ -z "$repository" ]]; then
    repository=$(basename "$(pwd)")
fi

if [[ -z "$target_branch" ]]; then
    target_branch=master
fi

if [[ -z "$source_branch" ]]; then
    source_branch=$(git rev-parse --abbrev-ref HEAD)
fi

# TODO: Save error to show
result=$(az repos pr create -p "$project" -r "$repository" -s "$source_branch" -t "$target_branch" --title "$title")

if [ $? -ne 0 ]; then
    echo "Error creating PR"
    exit 1
fi

# TODO: make this with other command (like grep)
pull_request_id=$(echo $result | jq '.pullRequestId')
base_url=$(echo $result | jq '.repository.webUrl' | tr -d '"')

echo ""
echo "PR: $base_url/pullrequest/$pull_request_id"
