#!/bin/bash

systemctl --user status spotifyd.service > /dev/null 2>&1

last_code=$?

case $last_code in
    4) # service inexsistent
        echo "spotifyd.service does not exist"
        exit 1
        ;;
    3) # deactivate
        systemctl --user start spotifyd.service > /dev/null
        ;;
    0) # active
        ;;
    *)
        echo "something went wrong with spotifyd.service"
        exit 1
        ;;
esac

spt
